# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        vendor_provider:
            entity:
              class: AppBundle:Vendeur
              property: email

    #Encodage des mots de passe
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
      AppBundle\Entity\Vendeur:
        algorithm: bcrypt


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        vendeur:
          pattern: ^/vendor
          provider: vendor_provider
          form_login:
            login_path: login_vendor
            check_path: login_vendor_check
            default_target_path: vendor_index
          logout:
            path: logout_vendor
            target: homepage

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

